/**
 * Three representative SME profiles used across the test suite, the demo seed
 * and the onboarding documentation.
 */

import type { Answers, CompanyProfile } from '@complisme/shared';

/**
 * 1. A 9-person Dutch SaaS company that ships an AI support assistant to
 *    customers: GDPR + AI Act + e-invoicing in scope, no CSRD.
 */
export const acme: CompanyProfile = {
  id: 'acme-saas',
  name: 'Acme Analytics BV',
  legalName: 'Acme Analytics B.V.',
  country: 'NL',
  sector: 'software',
  employees: 9,
  revenueEUR: 1_250_000,
  size: 'micro',
  frameworks: ['gdpr', 'eu-ai-act', 'e-invoicing'],
  aiSystems: [
    {
      id: 'ai-support',
      name: 'Support Copilot',
      purpose: 'Drafts replies to inbound customer support tickets and suggests knowledge base articles',
      domain: 'customer-service',
      deployed: true,
      interactsDirectlyWithNaturalPersons: true,
      vendors: ['OpenAI'],
      customTrained: false,
    },
  ],
  processingActivities: [
    {
      id: 'dpa-customers',
      name: 'Customer account administration',
      purpose: 'Contract administration, invoicing and support',
      legalBasis: 'contract',
      specialCategory: false,
      dataSubjects: ['customers', 'prospects'],
      dataCategories: ['name', 'email', 'billing address', 'support history'],
      retentionMonths: 120,
      processors: ['Stripe', 'Zendesk'],
      thirdCountryTransfers: ['US'],
      automatedDecisionMaking: false,
    },
    {
      id: 'dpa-telemetry',
      name: 'Product telemetry',
      purpose: 'Aggregate usage analytics for product improvement',
      legalBasis: 'legitimate-interest',
      specialCategory: false,
      dataSubjects: ['customers'],
      dataCategories: ['user id', 'session events', 'IP address'],
      retentionMonths: 14,
      processors: ['PostHog'],
      thirdCountryTransfers: [],
      automatedDecisionMaking: false,
    },
  ],
  hasDpo: false,
  hasRopa: true,
  hasDpia: false,
  hasSecurityPolicies: true,
  hasIncidentResponse: false,
  hasConsentMechanism: true,
  hostsDataInEu: true,
  usesCookies: true,
  notes: 'Customers ask for an EU AI Act transparency statement in procurement questionnaires.',
  createdAt: '2026-01-15T09:00:00.000Z',
  updatedAt: '2026-09-01T09:00:00.000Z',
};

/** Answers for a company that has done nothing yet — used to test worst cases. */
export const acmeColdStartAnswers: Answers = {};

/** Answers for a company that has most of the basics in place. */
export const acmeMatureAnswers: Answers = {
  gdpr: {
    'a5-q1': 'documented',
    'a5-q2': 'defined-and-automated',
    'a5-q3': true,
    'a5-q4': false,
    'a6-q1': false,
    'a6-q2': true,
    'a6-q3': false,
    'a6-q4': 'signed',
    'a7-q1': 'tested',
    'a7-q2': true,
    'a7-q3': true,
    'a7-q4': true,
    'a13-q1': true,
    'a13-q2': true,
    'a13-q3': true,
    'a25-q1': true,
    'a32-q1': true,
    'a32-q2': true,
    'a32-q3': true,
    'a33-q1': 'register-and-template',
    'a30-q1': 'complete-and-reviewed',
    'a30-q2': true,
    'a35-q1': 'not-required',
    'a35-q2': true,
    'a35-q3': 'n/a',
    'a37-q1': 'external',
    'a44-q1': 'complete',
    'a44-q2': true,
    'a44-q3': false,
    'a83-q1': true,
    'a83-q2': true,
    'a83-q3': true,
  },
  'eu-ai-act': {
    'a4-q1': 'documented-programme',
    'a4-q2': 'yes',
    'a4-q3': true,
    'a5-q1': 'all-screened',
    'a5-q2': false,
    'a5-q3': true,
    'a6-q1': 'documented',
    'a6-q2': true,
    'a9-q1': 'lifecycle-system',
    'a9-q2': false,
    'a9-q3': true,
    'a9-q4': 'partial',
    'a10-q1': 'n/a',
    'a10-q2': 'n/a',
    'a10-q3': 'n/a',
    'a10-q4': 'n/a',
    'a11-q1': 'draft',
    'a11-q2': true,
    'a11-q3': true,
    'a13-q1': true,
    'a13-q2': 'partial',
    'a13-q3': false,
    'a14-q1': 'partial',
    'a14-q2': true,
    'a14-q3': true,
    'a15-q1': 'qualitative',
    'a15-q2': false,
    'a15-q3': true,
    'a26-q1': 'assigned',
    'a26-q2': 'n/a',
    'a27-q1': 'not-required',
    'a27-q2': 'n/a',
    'a49-q1': 'not-required',
    'a50-q1': 'yes',
    'a50-q2': false,
    'a50-q3': 'n/a',
    'a72-q1': 'documented',
    'a72-q2': true,
    'a53-q1': true,
    'a53-q2': false,
    'a99-q1': true,
    'a99-q2': true,
    'a99-q3': false,
  },
  'e-invoicing': {
    'vida-q1': 'partial',
    'vida-q2': true,
    'vida-q3': true,
    'vida-q4': true,
    'vida-q5': true,
    'vida-q6': 'n/a',
    'vida-q7': true,
    'vida-q8': false,
    'vida-q9': false,
    'nfe-q1': 'n/a',
    'nfe-q2': 'n/a',
    'nfe-q3': 'n/a',
    'nfe-q4': 'n/a',
    'nfe-q5': 'n/a',
    'nfe-q6': 'n/a',
    'conf-q1': true,
    'conf-q2': false,
    'conf-q3': false,
    'ctrl-q1': true,
    'ctrl-q2': true,
    'ctrl-q3': false,
  },
};

/**
 * 2. A 140-person German automotive supplier: CSRD applies, GDPR and AI Act
 *    apply, no e-invoicing obligations yet.
 */
export const nordwerk: CompanyProfile = {
  id: 'nordwerk-ag',
  name: 'Nordwerk Automotive AG',
  legalName: 'Nordwerk Automotive AG',
  country: 'DE',
  sector: 'manufacturing',
  employees: 140,
  revenueEUR: 34_000_000,
  size: 'small',
  frameworks: ['csrd', 'gdpr', 'eu-ai-act'],
  aiSystems: [
    {
      id: 'ai-vision-qc',
      name: 'Visual quality inspection',
      purpose: 'Camera-based defect detection on the assembly line',
      domain: 'safety-component',
      deployed: true,
      vendors: ['internal'],
      customTrained: true,
      automatedDecisionMaking: false,
      notes: 'Safety component of a regulated product — likely high-risk under Art. 6(1).',
    },
    {
      id: 'ai-scheduling',
      name: 'Shift scheduling assistant',
      purpose: 'Suggests shift rosters to the production planner',
      domain: 'employment',
      deployed: true,
      vendors: ['internal'],
      customTrained: false,
      automatedDecisionMaking: true,
    },
  ],
  processingActivities: [
    {
      id: 'dpa-employees',
      name: 'Employee administration and time tracking',
      purpose: 'Payroll, time recording, occupational health',
      legalBasis: 'contract',
      specialCategory: true,
      dataSubjects: ['employees'],
      dataCategories: ['name', 'bank details', 'health data', 'performance data'],
      retentionMonths: 120,
      processors: ['DATEV'],
      thirdCountryTransfers: ['US'],
      automatedDecisionMaking: false,
    },
    {
      id: 'dpa-recruitment',
      name: 'Recruitment and applicant screening',
      purpose: 'CV screening and interview scheduling',
      legalBasis: 'consent',
      specialCategory: false,
      dataSubjects: ['applicants'],
      dataCategories: ['name', 'CV', 'interview notes', 'scores'],
      retentionMonths: 6,
      processors: ['Personio'],
      thirdCountryTransfers: ['US'],
      automatedDecisionMaking: true,
    },
  ],
  hasDpo: true,
  hasRopa: true,
  hasDpia: false,
  hasSecurityPolicies: true,
  hasIncidentResponse: true,
  hasConsentMechanism: true,
  hostsDataInEu: true,
  usesCookies: false,
  sustainability: {
    scope1TonnesCO2e: 1_850,
    scope2TonnesCO2e: 2_400,
    scope3TonnesCO2e: 48_000,
    energyMWh: 7_200,
    waterM3: 14_000,
    wasteTonnes: 620,
    renewableSharePct: 38,
    employeesFTE: 132,
    womenInLeadershipPct: 18,
    incidentsRecorded: 4,
    revenueEUR: 34_000_000,
    assuranceLevel: 'none',
    valueChainPolicies: false,
  },
  createdAt: '2026-01-20T09:00:00.000Z',
  updatedAt: '2026-09-01T09:00:00.000Z',
};

export const nordwerkAnswers: Answers = {
  csrd: {
    'esrs2-q1': 'documented',
    'esrs2-q2': 'informal',
    'esrs2-q3': false,
    'esrs2-q4': true,
    'esrs-s1-q1': 'estimated',
    'esrs-s1-q2': true,
    'esrs-s1-q3': false,
    'esrs-s1-q4': true,
    'esrs-s2-q1': 'partial',
    'esrs-s2-q2': true,
    'esrs-e1-q1': 'factors-only',
    'esrs-e1-q2': 'screened',
    'esrs-e1-q3': false,
    'esrs-e1-q4': true,
    'esrs-e1-q5': false,
    'esrs-e4-q1': true,
    'esrs-e3-q1': false,
    'esrs-e2-q1': true,
    'esrs-e5-q1': false,
    'esrs-g1-q1': true,
    'esrs-g1-q2': false,
    'esrs-g1-q3': true,
    'esrs-g1-q4': true,
    'csrd-q1': 'no',
    'csrd-q2': false,
    'csrd-q3': false,
    'csrd-q4': true,
    'csrd-q5': false,
    'csrd-q6': false,
  },
  gdpr: {
    'a5-q1': 'documented',
    'a5-q2': 'defined',
    'a5-q3': true,
    'a5-q4': true,
    'a6-q1': false,
    'a6-q2': true,
    'a6-q3': true,
    'a6-q4': 'pending',
    'a7-q1': 'documented',
    'a7-q2': false,
    'a7-q3': true,
    'a7-q4': true,
    'a13-q1': true,
    'a13-q2': true,
    'a13-q3': true,
    'a25-q1': true,
    'a32-q1': true,
    'a32-q2': true,
    'a32-q3': false,
    'a33-q1': 'register',
    'a30-q1': 'complete',
    'a30-q2': true,
    'a35-q1': 'required-missing',
    'a35-q2': true,
    'a35-q3': false,
    'a37-q1': 'appointed',
    'a44-q1': 'partial',
    'a44-q2': true,
    'a44-q3': true,
    'a83-q1': true,
    'a83-q2': false,
    'a83-q3': true,
  },
  'eu-ai-act': {
    'a4-q1': 'none',
    'a4-q2': 'no',
    'a4-q3': false,
    'a5-q1': 'none',
    'a5-q2': true,
    'a5-q3': false,
    'a6-q1': 'partial',
    'a6-q2': false,
    'a9-q1': 'none',
    'a9-q2': false,
    'a9-q3': false,
    'a9-q4': 'none',
    'a11-q1': 'none',
    'a11-q2': false,
    'a11-q3': false,
    'a13-q1': false,
    'a13-q2': 'no',
    'a13-q3': false,
    'a14-q1': 'no',
    'a14-q2': false,
    'a14-q3': false,
    'a15-q1': 'no',
    'a15-q2': false,
    'a15-q3': false,
    'a26-q1': 'partial',
    'a26-q2': false,
    'a27-q1': 'required-missing',
    'a27-q2': false,
    'a49-q1': 'no',
    'a50-q1': 'no',
    'a50-q2': false,
    'a50-q3': 'n/a',
    'a72-q1': 'no',
    'a72-q2': false,
    'a53-q1': false,
    'a53-q2': false,
    'a99-q1': false,
    'a99-q2': false,
    'a99-q3': false,
  },
};

/**
 * 3. A 4-person Brazilian consultancy selling services: NFS-e national
 *    e-invoicing is mandatory, GDPR applies because of EU clients.
 */
export function vistaSul(): CompanyProfile {
  return {
    id: 'vista-sul',
    name: 'Vista Sul Consultoria',
    legalName: 'Vista Sul Consultoria LTDA',
    country: 'BR',
    sector: 'consulting',
    employees: 4,
    revenueEUR: 320_000,
    size: 'micro',
    frameworks: ['e-invoicing', 'gdpr'],
    aiSystems: [],
    processingActivities: [
      {
        id: 'dpa-clients',
        name: 'Client engagement records',
        purpose: 'Contract management, invoicing and client deliverables',
        legalBasis: 'contract',
        specialCategory: false,
        dataSubjects: ['customers'],
        dataCategories: ['name', 'email', 'contract data'],
        retentionMonths: 120,
        processors: ['Google Workspace'],
        thirdCountryTransfers: ['US'],
        automatedDecisionMaking: false,
      },
    ],
    hasDpo: false,
    hasRopa: false,
    hasDpia: false,
    hasSecurityPolicies: false,
    hasIncidentResponse: false,
    hasConsentMechanism: false,
    hostsDataInEu: false,
    usesCookies: false,
    createdAt: '2026-02-01T09:00:00.000Z',
    updatedAt: '2026-09-01T09:00:00.000Z',
  };
}

export const vistaSulAnswers: Answers = {
  'e-invoicing': {
    'vida-q1': 'n/a',
    'vida-q2': false,
    'vida-q3': false,
    'vida-q4': false,
    'vida-q5': false,
    'vida-q6': 'n/a',
    'vida-q7': false,
    'vida-q8': false,
    'vida-q9': false,
    'nfe-q1': 'pdf-only',
    'nfe-q2': false,
    'nfe-q3': false,
    'nfe-q4': false,
    'nfe-q5': false,
    'nfe-q6': false,
    'conf-q1': false,
    'conf-q2': false,
    'conf-q3': false,
    'ctrl-q1': false,
    'ctrl-q2': false,
    'ctrl-q3': false,
  },
  gdpr: {
    'a5-q1': 'partial',
    'a5-q2': 'no',
    'a5-q3': false,
    'a5-q4': false,
    'a6-q1': false,
    'a6-q2': false,
    'a6-q3': false,
    'a6-q4': 'no',
    'a7-q1': 'no',
    'a7-q2': false,
    'a7-q3': false,
    'a7-q4': false,
    'a13-q1': false,
    'a13-q2': false,
    'a13-q3': false,
    'a25-q1': false,
    'a32-q1': false,
    'a32-q2': false,
    'a32-q3': false,
    'a33-q1': 'no',
    'a30-q1': 'no',
    'a30-q2': false,
    'a35-q1': 'unknown',
    'a35-q2': false,
    'a35-q3': false,
    'a37-q1': 'unknown',
    'a44-q1': 'no',
    'a44-q2': false,
    'a44-q3': false,
    'a83-q1': false,
    'a83-q2': false,
    'a83-q3': false,
  },
};

export const profiles: CompanyProfile[] = [acme, nordwerk, vistaSul()];

export function profileById(id: string): CompanyProfile | undefined {
  return profiles.find((p) => p.id === id);
}