/**
 * Document model shared by every template.
 *
 * Templates receive this structure (never the raw domain objects) so that adding
 * a regulation never requires touching the HTML, and so the LLM layer has a
 * single place to inject drafted narrative.
 */

import type {
  Answers,
  ComplianceScore,
  CompanyProfile,
  DocumentKind,
  Evidence,
  Framework,
  Gap,
  Roadmap,
} from '@complisme/shared';

export function escapeHtml(value: string): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export interface Branding {
  productName: string;
  tagline?: string;
  primaryColor: string;
  accentColor?: string;
  supportEmail?: string;
  website?: string;
  logoUrl?: string;
  preparedBy?: string;
  footerNote?: string;
}

export interface Section {
  id: string;
  heading: string;
  /** Pre-rendered HTML blocks (paragraphs, tables, lists). */
  body: string;
  /** Raw text, used for the DOCX writer and for word counts. */
  text?: string;
  level?: number;
  /** TOC entries before this section. */
  skipToc?: boolean;
}

export interface TocEntry {
  id: string;
  heading: string;
  level: number;
  page?: number;
}

export interface ChangeLogEntry {
  version: number;
  date: string;
  author?: string;
  summary: string;
}

export interface DocumentContext {
  kind: DocumentKind;
  title: string;
  subtitle?: string;
  /** Document control block rendered on page 1. */
  metadata: Array<{ label: string; value: string }>;
  sections: Section[];
  toc: TocEntry[];
  branding: Branding;
  generatedAt: string;
  company?: CompanyProfile;
  frameworks: Framework[];
  answers?: Answers;
  evidence?: Evidence[];
  scores?: ComplianceScore[];
  gaps?: Gap[];
  roadmap?: Roadmap;
  /** Free-form LLM-drafted narrative, keyed by section id. */
  narrative?: Record<string, string>;
  disclaimer?: string;
  changeLog?: ChangeLogEntry[];
  /** Data tables the DOCX writer converts. */
  tables?: Array<{ id: string; caption: string; headers: string[]; rows: string[][] }>;
}

export const DEFAULT_DISCLAIMER =
  'This document was generated by CompliSME from the information you provided. It is a compliance working ' +
  'document, not legal advice. Have it reviewed by a qualified lawyer or data protection officer before ' +
  'relying on it, and update it whenever your processing or systems change.';

export const DISCLAIMERS: Partial<Record<DocumentKind, string>> = {
  'ai-act-annex-iv':
    'This technical documentation is prepared under Annex IV of Regulation (EU) 2024/1689. Sections left as ' +
    '"TO BE COMPLETED" must be filled in with verified facts before the system is placed on the market. The ' +
    'information is a working document, not legal advice.',
  'gdpr-dpia':
    'A data protection impact assessment must be reviewed and signed by the data protection officer or, where ' +
    'no DPO is appointed, by the management body. This generated draft is not legal advice.',
  'csrd-report':
    'Sustainability reporting under the ESRS requires assurance and the accuracy of the reported data. This ' +
    'draft must be validated against the underlying records and is not legal or assurance advice.',
  'einvoice-validation-report':
    'Validation results describe the configuration observed at the time of the assessment. Tax authority ' +
    'acceptance must be confirmed against the current national rules.',
};